# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
paginate_path:      "page:num"
relative_permalinks: false

# Setup
title:               uvsankar
tagline:             'Yet another blog'
description:         'My Thoughts which I wanted to share with everyone'
url:                 https://uvsankar.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Sankar Varadarajan
  url:               https://uvsankar.github.io
  email:             uvsankar94@gmail.com

jekyll_analytics:
  GoogleAnalytics:
    id: UA-118573123-1
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Custom vars
version:             1.0.0

plugins:
  - jekyll-analytics
